version: '3'
services:
  springboot-app:
    container_name: containerisation
    image: springbootapp
    build: .
    ports:
      - 8080:8080
  mysqldb:
    container_name: mysqldb
    image: mysql
    ports:
      - 3307-3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root