spring:
  datasource:
    url: jdbc:mysql://book-cont:3306/book
    username: root
    password: $Aurabh123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true